version: "3"

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: /var/www
#    container_name: app
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./:/var/www
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
